version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: userstory-backend
    container_name: userstory-backend-node
    command: npm start
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3006:3006"
    depends_on:
      - mongo
  #  env_file: ./backend/.env
  #  environment:
  #    - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    container_name: userstory-mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: userstory-frontend
    container_name: userstory-frontend-react
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend # Bbbbb
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local